name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: Fetch Project
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true
    - name: Set up Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 16.3.0
    - name: Cache Bundle
      uses: actions/cache@v1
      with:
        path: bundle
        key: ${{ runner.OS }}-bundle-${{ hashFiles('Gemfile.lock') }}
    - name: Cache Node Modules
      uses: actions/cache@v1
      with:
        path: test/dummy/node_modules
        key: ${{ runner.OS }}-yarn-${{ hashFiles('test/dummy/yarn.lock') }}
    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install --path=bundle --jobs=4 --retry=3
        test/dummy/bin/yarn install --check-files
    - name: Prepare DB
      run: |
        bin/rails db:create
        bin/rails g rails_com:migrations --force
        bin/rails db:migrate
    - name: Run Test
      run: |
        bin/rails test -v -b
