name: Gem
on:
  create:
    tags:
    - 'v*'
jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Project
      uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ github.token }}
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${{ secrets.GEM_KEY }}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
